eo_airbrake:
  api_key: "%errbit_api_key%"
  host: errors.sumocoders.be

sumo_coders_framework_error:
  show_messages_for:
    - \Symfony\Component\HttpKernel\Exception\NotFoundHttpException

services:
  sumocoders_framework_error_bundle.twig.notifier_extension:
    class: SumoCoders\FrameworkErrorBundle\Twig\NotifierExtension
    tags:
      - { name: twig.extension }
    arguments:
      - @twig
      - %eo_airbrake.host%
      - %eo_airbrake.api_key%
